export const animales = [
  {
    id: 1,
    nombre: "Loki",
    descripcion: "Mi nombre es Loki. Soy juguetón, cariñoso y siempre está dispuesto a dar amor. Ideal para familias activas con niños.",
    imagen: "assets/img/perros/perrito2.jpg",
    tipo: "perro",
    edad: "1 año",
    raza: "Golden Retriever",
  },
  {
    id: 2,
    nombre: "Freya",
    descripcion: "Freya La princesa de casa. Es una gatita curiosa, sociable y muy tierna. Le encanta explorar y buscar cariño constantemente.",
    imagen: "assets/img/Gatos/Freya.jpeg",
    tipo: "gato",
    edad: "2 años",
    raza: "Curl Americano",
  },
  {
    id: 3,
    nombre: "Toby",
    descripcion: "Toby es un cachorro enérgico, le encanta correr y jugar. Necesita espacio y alguien con tiempo para compartir aventuras.",
    imagen: "assets/img/perros/perrito3.jpg",
    tipo: "perro",
    edad: "7 meses",
    raza: "Husky Siberiano",
  },
  {
    id: 4,
    nombre: "Pelusa",
    descripcion: "Pelusa es curiosa, dulce y le encanta dormir en lugares cálidos. Perfecta para quienes buscan un compañero tranquilo.",
    imagen: "assets/img/Gatos/gato1.jpeg",
    tipo: "gato",
    edad: "2 meses",
    raza: "Australian Mist",
  },
  {
    id: 5,
    nombre: "Mike",
    descripcion: "Mike super amigable, protector y muy inteligente, ideal para hogares con niños o espacios amplios para jugar.",
    imagen: "assets/img/perros/perrito4.jpg",
    tipo: "perro",
    edad: "1 años",
    raza: "Golden Retriever",
  },
  {
    id: 6,
    nombre: "Ataleya",
    descripcion: "Ataleya Tranquila, elegante y algo reservada, perfecta para un hogar sereno que valore su independencia.",
    imagen: "assets/img/Gatos/gato2.jpeg",
    tipo: "gato",
    edad: "2 meses",
    raza: "British Shorthair",
  },
  {
    id: 7,
    nombre: "Boby",
    descripcion: "Boby alegre, leal y muy sociable, siempre está listo para acompañarte a todos lados y darte cariño sin medida.",
    imagen: "assets/img/perros/perrito5.jpg",
    tipo: "perro",
    edad: "10 meses",
    raza: "border collie",
  }
];